'use strict';
module.exports = {
    USER_ROLE: 'user',
    ADMIN_ROLE: 'admin',
    MODERATOR_ROLE: 'moderator',
    MIN_USERNAME_LENGTH: 3,
    MAX_USERNAME_LENGTH: 20,
    MIN_PASSWORD_LENGTH: 6,
    MIN_TOKEN_LENGTH: 10,
    TOKEN_LENGTH: 200,
    TV_SERIES_DESCRIPTION_MAX_LENGTH: 500,
    SEASONS_PER_TV_SERIES_COUNT_FOR_SAMPLE_DATA: 5,
    EPISODES_PER_TV_SERIES_COUNT_FOR_SAMPLE_DATA: 20,
    MIN_TITLE_LENGTH: 1
};
